### ISSUE TITLE
No visual graphic page

### ISSUE THREAD

**Issue by yafengg** [RunqiuBao/kenki-positioning-vSLAM#1]
Hello，Why is there only code interface and no visual graphic page when running？

**Comment by yafengg** [comment]
May I contact you by email? thank you！This is my email address：<374745042@outlook.com>；

**Comment by RunqiuBao** [comment]
> Hello，Why is there only code interface and no visual graphic page when running？

Have you installed pangolin? please refer to `readme` for necessary dependencies.

**Comment by yafengg** [comment]
I installed it

**Comment by yafengg** [comment]
I installed it

**Comment by RunqiuBao** [comment]
> Why is there only code interface and no visual graphic page when running？

Can you post here your build logs?

**Comment by yafengg** [comment]
gyf@PC:~/SLAM/PaperCode/1/kenki-positioning-vSLAM$ ./build.sh
Configuring and building Thirdparty/DBoW2 ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:326: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Configuring and building Thirdparty/g2o ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:1016: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Uncompress vocabulary ...
tar: ORBvoc.txt.tar.gz：无法 open: 没有那个文件或目录
tar: Error is not recoverable: exiting now
Configuring and building ...
mkdir: 无法创建目录"build": 文件已存在
Build type: Release
-- Using flag -std=c++11.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/build
[ 92%] Built target kenki-posi
[100%] Built target stereo_ral

**Comment by yafengg** [comment]
gyf@PC:~/SLAM/PaperCode/1/kenki-positioning-vSLAM$ ./build.sh
Configuring and building Thirdparty/DBoW2 ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:326: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Configuring and building Thirdparty/g2o ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:1016: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Uncompress vocabulary ...
tar: ORBvoc.txt.tar.gz：无法 open: 没有那个文件或目录
tar: Error is not recoverable: exiting now
Configuring and building ...
mkdir: 无法创建目录"build": 文件已存在
Build type: Release
-- Using flag -std=c++11.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/build
[ 92%] Built target kenki-posi
[100%] Built target stereo_ral
gyf@PC:~/SLAM/PaperCode/1/kenki-positioning-vSLAM$

**Comment by yafengg** [comment]
gyf@PC:~/SLAM/PaperCode/kenki-positioning-vSLAM$ ./build.sh
Configuring and building Thirdparty/DBoW2 ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/kenki-positioning-vSLAM/Thirdparty/DBoW2/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/kenki-positioning-vSLAM/Thirdparty/DBoW2/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:326: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Configuring and building Thirdparty/g2o ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/kenki-positioning-vSLAM/Thirdparty/g2o/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/kenki-positioning-vSLAM/Thirdparty/g2o/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:1016: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Uncompress vocabulary ...
tar: ORBvoc.txt.tar.gz：无法 open: 没有那个文件或目录
tar: Error is not recoverable: exiting now
Configuring and building ...
mkdir: 无法创建目录"build": 文件已存在
Build type: Release
-- Using flag -std=c++11.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gyf/SLAM/PaperCode/kenki-positioning-vSLAM/build
[ 92%] Built target kenki-posi
[100%] Built target stereo_ral
gyf@PC:~/SLAM/PaperCode/kenki-positioning-vSLAM$

**Comment by yafengg** [comment]
```
gyf@PC:~/SLAM/PaperCode/1/kenki-positioning-vSLAM$ ./build.sh
Configuring and building Thirdparty/DBoW2 ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:326: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Configuring and building Thirdparty/g2o ...
mkdir: 无法创建目录"build": 文件已存在
CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
make: /usr/local/bin/cmake: Command not found
Makefile:1016: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 127
Uncompress vocabulary ...
tar: ORBvoc.txt.tar.gz：无法 open: 没有那个文件或目录
tar: Error is not recoverable: exiting now
Configuring and building ...
mkdir: 无法创建目录"build": 文件已存在
Build type: Release
-- Using flag -std=c++11.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/build
[ 92%] Built target kenki-posi
[100%] Built target stereo_ral
gyf@PC:~/SLAM/PaperCode/1/kenki-positioning-vSLAM$ 


```

**Comment by RunqiuBao** [comment]
> ```
> gyf@PC:~/SLAM/PaperCode/1/kenki-positioning-vSLAM$ ./build.sh
> Configuring and building Thirdparty/DBoW2 ...
> mkdir: 无法创建目录"build": 文件已存在
> CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
> CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/DBoW2/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/DBoW2/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
> make: /usr/local/bin/cmake: Command not found
> Makefile:326: recipe for target 'cmake_check_build_system' failed
> make: *** [cmake_check_build_system] Error 127
> Configuring and building Thirdparty/g2o ...
> mkdir: 无法创建目录"build": 文件已存在
> CMake Error: The current CMakeCache.txt directory /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/build/CMakeCache.txt is different than the directory /home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
> CMake Error: The source "/home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/Thirdparty/g2o/CMakeLists.txt" does not match the source "/home/runqiu/Desktop/ORB_SLAM2/code-opensource/kenki-posi/Thirdparty/g2o/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
> make: /usr/local/bin/cmake: Command not found
> Makefile:1016: recipe for target 'cmake_check_build_system' failed
> make: *** [cmake_check_build_system] Error 127
> Uncompress vocabulary ...
> tar: ORBvoc.txt.tar.gz：无法 open: 没有那个文件或目录
> tar: Error is not recoverable: exiting now
> Configuring and building ...
> mkdir: 无法创建目录"build": 文件已存在
> Build type: Release
> -- Using flag -std=c++11.
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/gyf/SLAM/PaperCode/1/kenki-positioning-vSLAM/build
> [ 92%] Built target kenki-posi
> [100%] Built target stereo_ral
> gyf@PC:~/SLAM/PaperCode/1/kenki-positioning-vSLAM$ 
> ```

Hi, I removed some build cache for the 3rdparty modules. 
Can you pull master and try build again?

**Comment by yafengg** [comment]
gyf@PC:~/SLAM/PaperCode/kenki-positioning-vSLAM/Examples/Stereo$ ./auto10.sh
maskThr: 0.6
frameskip: 10
refFrameDist: 3
usingColorImage: 1
_________________
The code can only run here, and there is still no output

**Comment by yafengg** [comment]
@RunqiuBao

**Comment by RunqiuBao** [comment]
> gyf@PC:~/SLAM/PaperCode/kenki-positioning-vSLAM/Examples/Stereo$ ./auto10.sh maskThr: 0.6 frameskip: 10 refFrameDist: 3 usingColorImage: 1
> 
> The code can only run here, and there is still no output

Can you try if you could see this viewer with the pangolin's hello world example:
![Screenshot from 2023-02-18 21-32-00](https://user-images.githubusercontent.com/35663368/219866510-61f17242-dbef-4fd5-97ff-e9def51b3079.png)

**Comment by yafengg** [comment]
Yes, I can see this viewer.

**Comment by RunqiuBao** [comment]
Hi, I still do not understand what issue you are having.
Can you investigate first what exactly issue you are having before asking for help?

**Comment by yafengg** [comment]
Unable to generate visualization window at runtime，As shown below：
![2c5766944569d59c0b668d320e0480eb](https://user-images.githubusercontent.com/102652842/219908039-dc0cc41c-6e20-48cf-827f-bffb7dfcd29d.png)

Can you upload the source code on github again? I noticed that someone commented on your code. Because this may cause a bug to the code.  Thank you!

**Comment by RunqiuBao** [comment]
? the code is already here, right? And it worked for me.
If you notices any bug, you can send a pull request to fix it.

And the viewer works for me. you need to find out why it did not work in your enviroment by yourself

**Comment by yafengg** [comment]
Ok, thank you for your help
